### ISSUE TITLE
Node order appears broken

### ISSUE THREAD

**Issue by hyanwong** [kitchensjn/tskit_arg_visualizer#68]
It looks like the default node order does *not* use the first tree. Attached is a tree seq of only one tree to demonstrate:

[node_order_viz_bug.trees.zip](https://github.com/user-attachments/files/16103315/node_order_viz_bug.trees.zip)

```python
ts = tskit.load("node_order_viz_bug.trees")
d3arg = tskit_arg_visualizer.D3ARG.from_ts(ts)
d3arg.draw(width=1150, height=400)
```
<img width="1079" alt="Screenshot 2024-07-05 at 00 09 51" src="https://github.com/kitchensjn/tskit_arg_visualizer/assets/4699014/18a50c22-3441-49bd-8fd4-b15360b996cc">

But if we order on the first tree, we get a nicer plot:

```python
d3arg.draw(width=1150, height=400, sample_order=list(ts.first().samples())
```
<img width="1095" alt="Screenshot 2024-07-05 at 00 11 55" src="https://github.com/kitchensjn/tskit_arg_visualizer/assets/4699014/3785efd8-14de-477f-aa32-89c13ff152fd">

**Comment by kitchensjn** [comment]
This was an issue in the v0.0.1 release (sample nodes are in increasing order rather than first tree) but I thought I had maybe fixed it since then. When I run your test tree sequence with the current GitHub main branch, it draws the same sample ordering as the first tree. Could you confirm which version of the code that you are using?

**Comment by hyanwong** [comment]
I simply installed from pip (testing this on colab at the moment).

```python
import tskit_arg_visualizer
tskit_arg_visualizer.__version__

AttributeError: module 'tskit_arg_visualizer' has no attribute '__version__'
```

Seems a bit odd. The installed `_vesrion.py` says:

```
__version__ = version = '0.0.2.dev23+g76ef6f7'
```

I will try reinstalling and see

**Comment by hyanwong** [comment]
However, installing from pip on colab (`!pip install --upgrade --target=xxx tskit_arg_visualizer`) says:

```
Collecting tskit_arg_visualizer
  Downloading tskit_arg_visualizer-0.0.1-py3-none-any.whl (17 kB)
...
Successfully installed .... tskit_arg_visualizer-0.0.1 

```

**Comment by hyanwong** [comment]
Hmm. Installing the dev version seems to have fixed it. Sorry for the noise!

**Comment by kitchensjn** [comment]
Not a problem! Always good to have these issues documented in some form like this. Correction on my side, this issue is not present in v0.0.1, but came about during v0.0.2 development. It was introduced in ff4963d and persisted until c3dd151 when I converted everything over to pandas.
